### ISSUE TITLE
Full outcomes does not work

### ISSUE THREAD

**Issue by ecboghiu** [ecboghiu/inflation#123]
**Describe the bug**

Uniform distribution feasibility is incorrect when using the `include_all_outcomes=True` on the devel branch at commit a4b23bcf81dd36976bc5d30f1c2393aba9d7430b

**To Reproduce**

```
import numpy as np
from inflation import InflationProblem, InflationLP

def P_PR(vis=1):
    p = np.zeros((2, 2, 2, 2))
    for a, b, x, y in np.ndindex(*p.shape):
        p[a, b, x, y] = \
            (1 + vis * (-1) ** (a + b + x*y)) / 8
    return p

scenario = InflationProblem(dag={'s': ['A', 'B']}, 
                            outcomes_per_party=[2, 2], 
                            settings_per_party=[2, 2],
                            inflation_level_per_source=(1,), 
                            classical_sources='all',
                            verbose=0)

v = 0
lp = InflationLP(scenario, include_all_outcomes=True)
lp.set_distribution(P_PR(vis=v))
lp.solve()
print(f"PR box feasibility for visibility (CG notation)= {v} :", lp.status)


v = 0
lp = InflationLP(scenario, include_all_outcomes=False)
lp.set_distribution(P_PR(vis=v))
lp.solve()
print(f"PR box feasibility for visibility (all outcomes)= {v} :", lp.status)

```

**Expected behavior**

Should be feasible.

**OS Information:**

-----------------
NumPy Version:  1.26.4
SciPy Version:  1.12.0
SymPy Version:  1.12
Numba Version:  0.59.0
Mosek Version:  10.1.24

Python Version: 3.10.13
Platform Info:  Darwin (arm64)

None

**Additional context**
.

**Comment by eliewolfe** [comment]
Bumping priority of this bug.

**Comment by apozas** [comment]
So, two things (one minor and one important):

- The minor one: the printouts are swapped, and that made debugging slightly complicated :sweat_smile: 
- The major one: there is **no bug**. The normalization is wrong. The denominator in L8 should be 4. Of course, the LP with `include_all_outcomes=True` fails because we are not setting a normalized probability distribution. On the other hand, `include_all_outcomes=False` runs because all the CG probabilities are still consistent with a normalized distribution (because, in fact, normalization is built-in). When using the correct normalization, both LPs are feasible for $v\leq0.5$ and infeasible otherwise.
